/* ============================================================
   PYTANIA NIEOFICJALNE — wygenerowane na podstawie sylabusa
   ISTQB CTFL v4.0. NIE są to oficjalne pytania ISTQB.
   Cel: maksymalne pokrycie celow nauczania (LO) calego sylabusa.
   Format identyczny jak QUESTIONS (app.js). id z prefiksem "P".
   ============================================================ */
window.PRACTICE = [

/* ================= ROZDZIAL 1 — Podstawy testowania ================= */
{n:1,id:"P1",ch:1,lo:"FL-1.1.1",k:"K1",sel:1,
 q:"Ktore z ponizszych NIE jest typowym celem testow?",
 opts:[["a","Wywolywanie awarii i wykrywanie defektow"],
   ["b","Budowanie zaufania do poziomu jakosci przedmiotu testow"],
   ["c","Naprawianie wykrytych defektow w kodzie"],
   ["d","Dostarczanie interesariuszom informacji do podejmowania decyzji"]],
 correct:["c"],
 exp:{a:"To typowy cel testow.",
   b:"To typowy cel testow.",
   c:"Poprawna. Naprawa defektow to debugowanie (zadanie programisty), a nie cel testowania. Testowanie wykrywa, ale nie usuwa defektow.",
   d:"To typowy cel testow."}},

{n:2,id:"P2",ch:1,lo:"FL-1.1.2",k:"K2",sel:1,
 q:"Czym rozni sie testowanie od debugowania?",
 opts:[["a","Testowanie usuwa przyczyny awarii, a debugowanie je wykrywa"],
   ["b","Testowanie dynamiczne moze wywolac awarie wskazujace na defekty; debugowanie znajduje, analizuje i usuwa ich przyczyny"],
   ["c","Testowanie i debugowanie to synonimy"],
   ["d","Debugowanie wykonuje sie wylacznie przed testowaniem"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Odwrocone role — to debugowanie usuwa przyczyny.",
   b:"Poprawna. Testowanie dynamiczne moze pokazac awarie spowodowane defektami; debugowanie to czynnosc programistyczna: reprodukcja, diagnoza (przyczyna zrodlowa) i naprawa.",
   c:"Niepoprawna. To dwie rozne czynnosci.",
   d:"Niepoprawna. Debugowanie nastepuje zwykle po wykryciu awarii w tescie."}},

{n:3,id:"P3",ch:1,lo:"FL-1.2.1",k:"K2",sel:1,
 q:"Ktory argument NAJLEPIEJ uzasadnia, dlaczego testowanie jest niezbedne?",
 opts:[["a","Testowanie gwarantuje, ze oprogramowanie jest w 100% wolne od defektow"],
   ["b","Testowanie przyczynia sie do sukcesu, redukujac ryzyko awarii w srodowisku operacyjnym i pomagajac spelnic wymagania kontraktowe/prawne"],
   ["c","Testowanie zastepuje potrzebe przegladow i analizy statycznej"],
   ["d","Testowanie eliminuje koniecznosc pisania wymagan"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Testowanie nie dowodzi braku defektow (zasada nr 1).",
   b:"Poprawna. Testowanie obniza ryzyko, weryfikuje i waliduje wymagania, pomaga spelnic zobowiazania kontraktowe, prawne i regulacyjne.",
   c:"Niepoprawna. Testowanie statyczne i dynamiczne sie uzupelniaja.",
   d:"Niepoprawna. Wymagania sa podstawa testow."}},

{n:4,id:"P4",ch:1,lo:"FL-1.2.2",k:"K1",sel:1,
 q:"Jaka jest relacja miedzy testowaniem a zapewnianiem jakosci (QA)?",
 opts:[["a","Testowanie i QA to to samo"],
   ["b","Testowanie (forma kontroli jakosci, QC) jest zorientowane na produkt i korygujace; QA jest zorientowane na proces i prewencyjne"],
   ["c","QA jest zorientowane na produkt, a testowanie na proces"],
   ["d","QA polega wylacznie na wykonywaniu testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To rozne pojecia.",
   b:"Poprawna. Testowanie to glowna forma kontroli jakosci (QC) — produktowa i korygujaca. QA jest procesowe i prewencyjne (dobry proces daje dobry produkt).",
   c:"Niepoprawna. Odwrocone definicje.",
   d:"Niepoprawna. QA dotyczy procesow, nie samego wykonywania testow."}},

{n:5,id:"P5",ch:1,lo:"FL-1.2.3",k:"K2",sel:1,
 q:"Programista zle zrozumial wymaganie i wpisal w kodzie zly wzor. Podczas dzialania program zwrocil bledny wynik. Wskaz prawidlowy lancuch przyczynowo-skutkowy.",
 opts:[["a","Awaria -> defekt -> pomylka"],
   ["b","Pomylka (zle zrozumienie) -> defekt (zly wzor w kodzie) -> awaria (bledny wynik)"],
   ["c","Defekt -> pomylka -> awaria"],
   ["d","Pomylka -> awaria -> defekt"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Kolejnosc odwrocona.",
   b:"Poprawna. Czlowiek popelnia pomylke, ktora wprowadza defekt do produktu pracy; uruchomienie defektu moze wywolac awarie.",
   c:"Niepoprawna. Pomylka jest pierwsza.",
   d:"Niepoprawna. Defekt poprzedza awarie."}},

{n:6,id:"P6",ch:1,lo:"FL-1.2.3",k:"K2",sel:1,
 q:"Co moze byc przyczyna awarii NIEZWIAZANA z defektem w kodzie?",
 opts:[["a","Pomylka programisty"],
   ["b","Warunki srodowiskowe, np. promieniowanie lub pole magnetyczne wplywajace na sprzet"],
   ["c","Brak przypadkow testowych"],
   ["d","Zle zrozumienie wymagania"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To prowadzi do defektu.",
   b:"Poprawna. Awarie moga wynikac rowniez z warunkow srodowiskowych (promieniowanie, zaklocenia, zanieczyszczenia) wplywajacych na dzialanie sprzetu, a nie tylko z defektow.",
   c:"Niepoprawna. To nie powoduje awarii uruchomieniowej.",
   d:"Niepoprawna. To prowadzi do defektu."}},

{n:7,id:"P7",ch:1,lo:"FL-1.3.1",k:"K2",sel:1,
 q:"Zespol planuje przetestowac wszystkie mozliwe kombinacje danych wejsciowych formularza. Ktora zasada testowania wskazuje, ze to bledne podejscie?",
 opts:[["a","Testowanie pokazuje obecnosc defektow"],
   ["b","Testowanie pelne (wyczerpujace) jest niewykonalne"],
   ["c","Defekty wystepuja w skupiskach"],
   ["d","Wczesne testowanie oszczedza czas i pieniadze"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Ta zasada mowi, ze testy wykrywaja defekty, ale nie dowodza ich braku.",
   b:"Poprawna. Poza trywialnymi przypadkami testowanie wszystkich kombinacji jest niewykonalne; nalezy stosowac techniki i analize ryzyka do priorytetyzacji.",
   c:"Niepoprawna. Ta zasada dotyczy koncentracji defektow.",
   d:"Niepoprawna. Ta zasada dotyczy korzysci z wczesnego testowania."}},

{n:8,id:"P8",ch:1,lo:"FL-1.3.1",k:"K2",sel:1,
 q:"Zasada „testy sie zuzywaja” (paradoks pestycydow) sugeruje, ze:",
 opts:[["a","Te same testy powtarzane wielokrotnie z czasem przestaja wykrywac nowe defekty i nalezy je przegladac i aktualizowac"],
   ["b","Testy nalezy wykonywac tylko raz"],
   ["c","Im wiecej testow, tym mniej defektow w kodzie"],
   ["d","Defekty zawsze koncentruja sie w jednym module"]],
 correct:["a"],
 exp:{a:"Poprawna. Powtarzane bez zmian testy traca skutecznosc; aby wykrywac nowe defekty, testy i dane testowe trzeba regularnie przegladac i modyfikowac, dodawac nowe.",
   b:"Niepoprawna. Wrecz przeciwnie — np. regresja wymaga powtarzania, ale testy trzeba odnawiac.",
   c:"Niepoprawna. To nie tresc tej zasady.",
   d:"Niepoprawna. To zasada o skupiskach defektow."}},

{n:9,id:"P9",ch:1,lo:"FL-1.4.1",k:"K2",sel:1,
 q:"Do ktorej czynnosci testowej nalezy definiowanie warunkow testowych (co testowac)?",
 opts:[["a","Planowanie testow"],
   ["b","Analiza testow"],
   ["c","Projektowanie testow"],
   ["d","Wykonywanie testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Planowanie definiuje cele i podejscie.",
   b:"Poprawna. Analiza testow odpowiada na pytanie „co testowac?” — wyznacza warunki testowe na podstawie analizy podstawy testow.",
   c:"Niepoprawna. Projektowanie odpowiada na „jak testowac?” (przypadki, elementy pokrycia).",
   d:"Niepoprawna. Wykonywanie to uruchamianie testow."}},

{n:10,id:"P10",ch:1,lo:"FL-1.4.2",k:"K2",sel:1,
 q:"Ktory czynnik kontekstu ma ISTOTNY wplyw na proces testowy?",
 opts:[["a","Kolor interfejsu uzytkownika aplikacji"],
   ["b","Model cyklu zycia oprogramowania (SDLC) oraz zidentyfikowane ryzyka produktowe"],
   ["c","Liczba commitow w repozytorium z zeszlego roku"],
   ["d","Marka komputerow uzywanych przez zespol"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Nieistotny dla procesu testowego.",
   b:"Poprawna. Na proces testowy wplywaja m.in.: interesariusze, zespol, dziedzina biznesowa, czynniki techniczne, model SDLC, ograniczenia projektowe i ryzyka produktowe.",
   c:"Niepoprawna. Nieistotny czynnik.",
   d:"Niepoprawna. Nieistotny czynnik."}},

{n:11,id:"P11",ch:1,lo:"FL-1.4.3",k:"K2",sel:1,
 q:"Ktory z ponizszych produktow pracy jest TESTALIAMI (testware) powstajacymi w czynnosci analizy testow?",
 opts:[["a","Warunki testowe"],
   ["b","Skrypty testowe"],
   ["c","Raporty o postepie testow"],
   ["d","Dane testowe"]],
 correct:["a"],
 exp:{a:"Poprawna. Analiza testow wytwarza warunki testowe.",
   b:"Niepoprawna. Skrypty powstaja w implementacji testow.",
   c:"Niepoprawna. Raporty powstaja w monitorowaniu i nadzorze.",
   d:"Niepoprawna. Dane testowe powstaja w implementacji testow."}},

{n:12,id:"P12",ch:1,lo:"FL-1.4.4",k:"K2",sel:1,
 q:"Jaka jest glowna wartosc utrzymywania identyfikowalnosci (traceability) miedzy podstawa testow a testaliami?",
 opts:[["a","Przyspiesza kompilacje kodu"],
   ["b","Umozliwia ocene pokrycia, analize wplywu zmian, audytowalnosc oraz zrozumiale raportowanie postepu"],
   ["c","Eliminuje potrzebe pisania przypadkow testowych"],
   ["d","Gwarantuje brak defektow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Bez zwiazku z kompilacja.",
   b:"Poprawna. Identyfikowalnosc wspiera ocene pokrycia wzgledem wymagan, analize wplywu zmian, audyty oraz raportowanie w kategoriach zrozumialych dla interesariuszy.",
   c:"Niepoprawna. Nie zastepuje projektowania testow.",
   d:"Niepoprawna. Nic nie gwarantuje braku defektow."}},

{n:13,id:"P13",ch:1,lo:"FL-1.4.5",k:"K2",sel:1,
 q:"Ktore zadanie nalezy GLOWNIE do roli zarzadzania testami (a nie roli testowania)?",
 opts:[["a","Projektowanie przypadkow testowych"],
   ["b","Wykonywanie testow i raportowanie defektow"],
   ["c","Planowanie testow oraz monitorowanie i nadzor nad postepem"],
   ["d","Implementacja danych testowych"]],
 correct:["c"],
 exp:{a:"Niepoprawna. To rola testowania (aspekt inzynierski).",
   b:"Niepoprawna. To rola testowania.",
   c:"Poprawna. Rola zarzadzania testami obejmuje planowanie, monitorowanie i nadzor oraz ukonczenie testow, a takze przywodztwo nad procesem i zespolem.",
   d:"Niepoprawna. To rola testowania."}},

{n:14,id:"P14",ch:1,lo:"FL-1.5.1",k:"K2",sel:1,
 q:"Ktora z ponizszych jest przykladem umiejetnosci OGOLNEJ szczegolnie waznej dla testera?",
 opts:[["a","Umiejetnosc programowania w jezyku asemblera"],
   ["b","Myslenie krytyczne i analityczne oraz dbalosc o szczegoly"],
   ["c","Znajomosc historii informatyki"],
   ["d","Umiejetnosc projektowania logo produktu"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To waska umiejetnosc techniczna, nie ogolna.",
   b:"Poprawna. Do umiejetnosci ogolnych testera naleza m.in.: myslenie krytyczne i analityczne, skrupulatnosc, komunikacja, praca zespolowa, kreatywnosc, wiedza dziedzinowa.",
   c:"Niepoprawna. Nieistotna.",
   d:"Niepoprawna. Nieistotna dla roli testera."}},

{n:15,id:"P15",ch:1,lo:"FL-1.5.2",k:"K1",sel:1,
 q:"Jaka jest glowna zaleta podejscia calego zespolu (whole team approach)?",
 opts:[["a","Tylko testerzy odpowiadaja za jakosc"],
   ["b","Szeroki zakres umiejetnosci w zespole i wspolna odpowiedzialnosc za jakosc poprawiaja komunikacje i wspolprace"],
   ["c","Eliminuje potrzebe testowania"],
   ["d","Programisci nie musza pisac zadnych testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Za jakosc odpowiada caly zespol.",
   b:"Poprawna. Dzieki roznorodnym umiejetnosciom i wspolnej odpowiedzialnosci za jakosc zespol lepiej sie komunikuje i wspolpracuje (synergia); wspollokalizacja to wzmacnia.",
   c:"Niepoprawna. Testowanie nadal jest potrzebne.",
   d:"Niepoprawna. Programisci uczestnicza w testowaniu (np. komponentow)."}},

{n:16,id:"P16",ch:1,lo:"FL-1.5.3",k:"K2",sel:1,
 q:"Ktore stwierdzenie o niezaleznosci testowania jest prawdziwe?",
 opts:[["a","Wieksza niezaleznosc zawsze gwarantuje wykrycie wszystkich defektow"],
   ["b","Pewien stopien niezaleznosci sprzyja wykrywaniu roznych defektow (inne spojrzenie), ale zbyt duza moze powodowac problemy z komunikacja i izolacje od zespolu"],
   ["c","Autor produktu wykrywa wlasne defekty rownie skutecznie jak osoba niezalezna"],
   ["d","Niezaleznosc testowania nie ma zadnych wad"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Niezaleznosc nie gwarantuje wykrycia wszystkich defektow.",
   b:"Poprawna. Niezaleznosc daje inne spojrzenie i wykrywa rozne defekty, ale ma wady: ryzyko izolacji, gorszej komunikacji, postrzegania testera jako „waskiego gardla”.",
   c:"Niepoprawna. Autor ma tendencyjne nastawienie i przeocza wlasne pomylki.",
   d:"Niepoprawna. Ma wady (np. izolacja, komunikacja)."}},

/* ================= ROZDZIAL 2 — Testowanie w cyklu zycia ================= */
{n:17,id:"P17",ch:2,lo:"FL-2.1.1",k:"K2",sel:1,
 q:"Jak wybor sekwencyjnego modelu SDLC (np. V) wplywa na testowanie w porownaniu z modelem zwinnym?",
 opts:[["a","W modelu sekwencyjnym testowanie dynamiczne jest zwykle skoncentrowane w pozniejszych fazach, gdy dostepny jest dzialajacy kod"],
   ["b","Model sekwencyjny nie pozwala na testowanie statyczne"],
   ["c","W modelu zwinnym nie wykonuje sie testowania regresji"],
   ["d","Wybor SDLC nie ma zadnego wplywu na testowanie"]],
 correct:["a"],
 exp:{a:"Poprawna. W modelach sekwencyjnych kod powstaje pozno, wiec testowanie dynamiczne jest ograniczone do pozniejszych faz; testowanie statyczne mozna prowadzic wczesnie.",
   b:"Niepoprawna. Testowanie statyczne (przeglady) jest mozliwe od poczatku.",
   c:"Niepoprawna. W modelach zwinnych regresja jest wrecz intensywna.",
   d:"Niepoprawna. SDLC istotnie wplywa na zakres, czas i poziomy testow."}},

{n:18,id:"P18",ch:2,lo:"FL-2.1.2",k:"K1",sel:1,
 q:"Ktora praktyka jest dobra praktyka testowania majaca zastosowanie we WSZYSTKICH modelach SDLC?",
 opts:[["a","Testerzy powinni dolaczac do projektu dopiero po zakonczeniu kodowania"],
   ["b","Dla kazdej czynnosci wytworczej istnieje odpowiadajaca jej czynnosc testowa, a kazdy poziom testow ma swoje specyficzne cele"],
   ["c","Testowanie statyczne nalezy pomijac w projektach zwinnych"],
   ["d","Testerzy nie powinni uczestniczyc w przegladach wymagan"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Wczesne zaangazowanie testerow to dobra praktyka.",
   b:"Poprawna. Do dobrych praktyk niezaleznych od SDLC naleza: odpowiadanie czynnosci testowych czynnosciom wytworczym, rozne cele roznych poziomow testow, wczesne projektowanie testow i zaangazowanie testerow.",
   c:"Niepoprawna. Testowanie statyczne jest wartoscia w kazdym modelu.",
   d:"Niepoprawna. Udzial testerow w przegladach jest zalecany."}},

{n:19,id:"P19",ch:2,lo:"FL-2.1.3",k:"K1",sel:1,
 q:"Ktore z ponizszych sa przykladami podejsc „najpierw test” (test-first)?",
 opts:[["a","Waterfall, Spiral, RUP"],
   ["b","TDD, ATDD, BDD"],
   ["c","Kanban, Scrum, SAFe"],
   ["d","UML, BPMN, ERD"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To modele/procesy wytworcze.",
   b:"Poprawna. Podejscia test-first to: wytwarzanie sterowane testami (TDD), sterowane testami akceptacyjnymi (ATDD) oraz sterowane zachowaniem (BDD).",
   c:"Niepoprawna. To metody/frameworki zwinne.",
   d:"Niepoprawna. To jezyki/notacje modelowania."}},

{n:20,id:"P20",ch:2,lo:"FL-2.1.4",k:"K2",sel:1,
 q:"Ktory z ponizszych jest RYZYKIEM (a nie zaleta) DevOps z perspektywy testowania?",
 opts:[["a","Szybka informacja zwrotna o jakosci kodu"],
   ["b","Automatyczna regresja w potoku CI/CD"],
   ["c","Ryzyko niedoceniania wartosci testow manualnych oraz koszt i zlozonosc wdrozenia frameworka automatyzacji"],
   ["d","Czestsze i szybsze wydania"]],
 correct:["c"],
 exp:{a:"Niepoprawna. To zaleta DevOps.",
   b:"Niepoprawna. To zaleta DevOps.",
   c:"Poprawna. DevOps niesie ryzyka: potrzeba zaprojektowania i utrzymania potoku, koszt frameworka automatyzacji, mozliwe pomijanie wartosci testow manualnych/eksploracyjnych.",
   d:"Niepoprawna. To zaleta DevOps."}},

{n:21,id:"P21",ch:2,lo:"FL-2.1.5",k:"K2",sel:1,
 q:"Co najlepiej opisuje podejscie „przesuniecie w lewo” (shift-left)?",
 opts:[["a","Przenoszenie wszystkich testow na koniec projektu"],
   ["b","Wczesniejsze rozpoczynanie czynnosci testowych w cyklu zycia (np. wczesne przeglady, TDD, wczesne testy niefunkcjonalne)"],
   ["c","Rezygnacja z testowania statycznego"],
   ["d","Testowanie wylacznie po wdrozeniu na produkcje"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To przeciwienstwo shift-left.",
   b:"Poprawna. Shift-left oznacza wczesniejsze testowanie: przeglady wymagan, pisanie testow przed kodem, wczesne testy niefunkcjonalne — tansze wykrywanie defektow.",
   c:"Niepoprawna. Shift-left wlasnie promuje wczesne testowanie statyczne.",
   d:"Niepoprawna. To przeciwienstwo idei."}},

{n:22,id:"P22",ch:2,lo:"FL-2.1.6",k:"K2",sel:1,
 q:"W jaki sposob retrospektywy wspieraja doskonalenie procesu testowego?",
 opts:[["a","Sa spotkaniem, na ktorym ustala sie wymagania na kolejna iteracje"],
   ["b","Pozwalaja zespolowi przeanalizowac, co poszlo dobrze i zle, oraz uzgodnic usprawnienia (np. w testowaniu, narzedziach, wspolpracy)"],
   ["c","Sluza wylacznie do oceny wydajnosci poszczegolnych osob"],
   ["d","Zastepuja planowanie testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To cel spotkan planistycznych, nie retrospektywy.",
   b:"Poprawna. Retrospektywy (na koniec iteracji/wydania) sluza ciaglemu doskonaleniu: identyfikacji sukcesow, problemow i usprawnien procesu, w tym testowego.",
   c:"Niepoprawna. To nie ocena indywidualna.",
   d:"Niepoprawna. Nie zastepuja planowania."}},

{n:23,id:"P23",ch:2,lo:"FL-2.2.1",k:"K2",sel:1,
 q:"Zespol testuje interakcje miedzy modulem platnosci a baza danych w obrebie jednej aplikacji. Ktory to poziom testow?",
 opts:[["a","Testowanie komponentow"],
   ["b","Testowanie integracji komponentow"],
   ["c","Testowanie integracji systemow"],
   ["d","Testowanie akceptacyjne"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To dotyczy pojedynczego komponentu w izolacji.",
   b:"Poprawna. Testowanie integracji komponentow sprawdza interakcje i interfejsy miedzy komponentami tego samego systemu.",
   c:"Niepoprawna. Integracja systemow dotyczy interfejsow z innymi (zewnetrznymi) systemami.",
   d:"Niepoprawna. Akceptacyjne dotyczy gotowosci biznesowej."}},

{n:24,id:"P24",ch:2,lo:"FL-2.2.2",k:"K2",sel:1,
 q:"Test sprawdzajacy czas odpowiedzi systemu pod duzym obciazeniem to przyklad testowania:",
 opts:[["a","Funkcjonalnego"],
   ["b","Niefunkcjonalnego (charakterystyka: wydajnosc)"],
   ["c","Potwierdzajacego"],
   ["d","Bialoskrzynkowego"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Funkcjonalne sprawdza, CO system robi.",
   b:"Poprawna. Testowanie niefunkcjonalne sprawdza, JAK DOBRZE system dziala — tu wydajnosc/efektywnosc.",
   c:"Niepoprawna. Potwierdzajace dotyczy weryfikacji naprawy defektu.",
   d:"Niepoprawna. To nie technika oparta na strukturze kodu."}},

{n:25,id:"P25",ch:2,lo:"FL-2.2.3",k:"K2",sel:1,
 q:"Po naprawie defektu tester ponownie uruchamia test, ktory wczesniej wykryl awarie, aby sprawdzic czy defekt zostal usuniety. To:",
 opts:[["a","Testowanie regresji"],
   ["b","Testowanie potwierdzajace (confirmation testing)"],
   ["c","Testowanie pielegnacyjne"],
   ["d","Testowanie eksploracyjne"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Regresja sprawdza, czy zmiany nie zepsuly innych czesci.",
   b:"Poprawna. Testowanie potwierdzajace (retest) sprawdza, czy pierwotny defekt zostal skutecznie naprawiony.",
   c:"Niepoprawna. Pielegnacyjne dotyczy zmian w dzialajacym systemie.",
   d:"Niepoprawna. Eksploracyjne to technika oparta na doswiadczeniu."}},

{n:26,id:"P26",ch:2,lo:"FL-2.3.1",k:"K2",sel:1,
 q:"Ktore z ponizszych jest typowym WYZWALACZEM testowania pielegnacyjnego (maintenance testing)?",
 opts:[["a","Pierwsze napisanie nowego komponentu w projekcie greenfield"],
   ["b","Modyfikacje, migracja na nowe srodowisko/platforme lub wycofanie (retirement) systemu"],
   ["c","Projektowanie przypadkow testowych dla nowej funkcji"],
   ["d","Przeglad wymagan przed rozpoczeciem kodowania"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To prace nad nowym systemem, nie pielegnacja.",
   b:"Poprawna. Wyzwalacze pielegnacji: modyfikacje i ulepszenia, migracja danych/srodowiska, wycofanie systemu (w tym testy migracji i archiwizacji danych).",
   c:"Niepoprawna. To czynnosc projektowania testow.",
   d:"Niepoprawna. To testowanie statyczne."}},

/* ================= ROZDZIAL 3 — Testowanie statyczne ================= */
{n:27,id:"P27",ch:3,lo:"FL-3.1.1",k:"K1",sel:1,
 q:"Ktory z ponizszych produktow pracy MOZE byc badany technikami testowania statycznego?",
 opts:[["a","Tylko gotowy, skompilowany kod wykonywalny"],
   ["b","Niemal kazdy produkt pracy, ktory da sie przeczytac i zrozumiec: wymagania, kod zrodlowy, plany testow, umowy, modele"],
   ["c","Wylacznie dane testowe"],
   ["d","Tylko dziennik (log) z wykonania testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Testowanie statyczne nie uruchamia kodu.",
   b:"Poprawna. Statycznie mozna badac szeroki zakres produktow: specyfikacje, historyjki, kryteria akceptacji, kod zrodlowy, plany testow, umowy, modele, strony www.",
   c:"Niepoprawna. To zbyt waskie.",
   d:"Niepoprawna. Log powstaje dopiero z wykonania (testowanie dynamiczne)."}},

{n:28,id:"P28",ch:3,lo:"FL-3.1.2",k:"K2",sel:1,
 q:"Jaka jest kluczowa wartosc testowania statycznego?",
 opts:[["a","Pozwala zmierzyc czas odpowiedzi systemu"],
   ["b","Umozliwia wczesne wykrywanie defektow zanim powstanie kod, co obniza koszt ich usuniecia"],
   ["c","Zastepuje calkowicie testowanie dynamiczne"],
   ["d","Dziala wylacznie po wdrozeniu systemu"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To domena testow wydajnosciowych (dynamicznych).",
   b:"Poprawna. Statyczne testowanie wykrywa defekty najwczesniej (np. w wymaganiach), gdy ich naprawa jest najtansza; znajduje tez defekty, ktorych testy dynamiczne moga nie ujawnic.",
   c:"Niepoprawna. Oba podejscia sie uzupelniaja.",
   d:"Niepoprawna. Stosuje sie je wczesnie w cyklu zycia."}},

{n:29,id:"P29",ch:3,lo:"FL-3.1.3",k:"K2",sel:1,
 q:"Czym rozni sie testowanie statyczne od dynamicznego?",
 opts:[["a","Statyczne uruchamia kod, dynamiczne tylko go czyta"],
   ["b","Statyczne bada produkt bez uruchamiania kodu i znajduje defekty bezposrednio; dynamiczne wymaga uruchomienia i wykrywa awarie spowodowane defektami"],
   ["c","Oba wymagaja uruchomienia oprogramowania"],
   ["d","Dynamiczne wykrywa defekty wczesniej niz statyczne"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Role odwrocone.",
   b:"Poprawna. Statyczne nie uruchamia kodu i wskazuje defekty wprost; dynamiczne uruchamia oprogramowanie i obserwuje awarie. Roznia sie tez typami wykrywanych defektow.",
   c:"Niepoprawna. Statyczne nie wymaga uruchomienia.",
   d:"Niepoprawna. To statyczne pozwala wykryc defekty najwczesniej."}},

{n:30,id:"P30",ch:3,lo:"FL-3.2.1",k:"K1",sel:1,
 q:"Jaka jest glowna korzysc z wczesnej i czestej informacji zwrotnej od interesariuszy?",
 opts:[["a","Eliminuje potrzebe testowania dynamicznego"],
   ["b","Pozwala wczesnie wykryc nieporozumienia co do wymagan i unikac kosztownych zmian na pozniejszych etapach"],
   ["c","Gwarantuje brak defektow w kodzie"],
   ["d","Zwieksza liczbe wymagan w projekcie"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Nie zastepuje testow dynamicznych.",
   b:"Poprawna. Wczesna i czesta informacja zwrotna pozwala wczesnie ujawnic potencjalne problemy z wymaganiami i zmniejsza ryzyko kosztownych poprawek pozniej.",
   c:"Niepoprawna. Nic nie gwarantuje braku defektow.",
   d:"Niepoprawna. To nie cel informacji zwrotnej."}},

{n:31,id:"P31",ch:3,lo:"FL-3.2.2",k:"K2",sel:1,
 q:"Ktora jest prawidlowa kolejnoscia (uproszczona) czynnosci procesu przegladu wg ISTQB?",
 opts:[["a","Przeglad indywidualny -> planowanie -> komunikacja i analiza wynikow"],
   ["b","Planowanie -> rozpoczecie przegladu -> przeglad indywidualny -> komunikacja i analiza -> naprawa i raportowanie"],
   ["c","Naprawa -> planowanie -> przeglad indywidualny"],
   ["d","Komunikacja wynikow -> planowanie -> rozpoczecie przegladu"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Planowanie jest pierwsze.",
   b:"Poprawna. Czynnosci przegladu: planowanie, rozpoczecie przegladu, przeglad indywidualny (analiza), komunikacja i analiza wynikow, naprawa i raportowanie.",
   c:"Niepoprawna. Zla kolejnosc.",
   d:"Niepoprawna. Zla kolejnosc."}},

{n:32,id:"P32",ch:3,lo:"FL-3.2.3",k:"K1",sel:1,
 q:"Kto w procesie przegladu pelni role kierownika przegladu / facylitatora (moderatora) odpowiedzialnego za sprawny przebieg spotkania?",
 opts:[["a","Autor"],
   ["b","Facylitator (moderator)"],
   ["c","Protokolant (scribe)"],
   ["d","Kierownik (manager)"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Autor tworzy i poprawia przedmiot przegladu.",
   b:"Poprawna. Facylitator (moderator) zapewnia skuteczny przebieg spotkan przegladowych, mediuje i dba o bezpieczna atmosfere.",
   c:"Niepoprawna. Protokolant zapisuje uwagi i decyzje.",
   d:"Niepoprawna. Kierownik decyduje o przegladzie i zasobach, ale nie prowadzi spotkania."}},

{n:33,id:"P33",ch:3,lo:"FL-3.2.4",k:"K2",sel:1,
 q:"Ktory typ przegladu jest najbardziej sformalizowany, prowadzony wg zdefiniowanego procesu z metrykami i okreslonymi rolami?",
 opts:[["a","Przeglad nieformalny (informal review)"],
   ["b","Przejrzenie (walkthrough)"],
   ["c","Przeglad techniczny (technical review)"],
   ["d","Inspekcja (inspection)"]],
 correct:["d"],
 exp:{a:"Niepoprawna. Najmniej formalny, bez zdefiniowanego procesu.",
   b:"Niepoprawna. Prowadzony zwykle przez autora, sredni poziom formalnosci.",
   c:"Niepoprawna. Wykonywany przez ekspertow technicznych, ale mniej formalny niz inspekcja.",
   d:"Poprawna. Inspekcja jest najbardziej formalna: zdefiniowany proces, role, kryteria wejscia/wyjscia, zbieranie metryk."}},

{n:34,id:"P34",ch:3,lo:"FL-3.2.5",k:"K1",sel:1,
 q:"Ktory czynnik przyczynia sie do SUKCESU przegladu?",
 opts:[["a","Traktowanie znalezionych defektow jako oceny autora"],
   ["b","Jasne cele przegladu, odpowiedni typ dla danego produktu i atmosfera oparta na zaufaniu (bez oceniania osob)"],
   ["c","Maksymalnie duzy dokument przegladany na jednym spotkaniu"],
   ["d","Brak przygotowania uczestnikow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Wyniki nie powinny sluzyc ocenie autorow.",
   b:"Poprawna. Sukces sprzyjaja: jasne cele, wlasciwy typ przegladu, niewielki rozmiar porcji, przygotowanie, atmosfera zaufania, docenianie i uczenie sie.",
   c:"Niepoprawna. Zbyt duze porcje obnizaja skutecznosc.",
   d:"Niepoprawna. Brak przygotowania szkodzi przegladowi."}},

/* ================= ROZDZIAL 4 — Analiza i projektowanie testow ================= */
{n:35,id:"P35",ch:4,lo:"FL-4.1.1",k:"K2",sel:1,
 q:"Czym charakteryzuja sie techniki testowania oparte na doswiadczeniu (experience-based)?",
 opts:[["a","Wykorzystuja wewnetrzna strukture kodu do wyznaczania pokrycia"],
   ["b","Wykorzystuja wiedze i doswiadczenie testerow do projektowania testow (np. zgadywanie bledow, testy eksploracyjne)"],
   ["c","Sa oparte wylacznie na formalnej specyfikacji wymagan"],
   ["d","Mierza pokrycie instrukcji i galezi"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To techniki bialoskrzynkowe.",
   b:"Poprawna. Techniki oparte na doswiadczeniu korzystaja z wiedzy, intuicji i doswiadczenia testerow; naleza do nich zgadywanie bledow, testowanie eksploracyjne i oparte na listach kontrolnych.",
   c:"Niepoprawna. To techniki czarnoskrzynkowe.",
   d:"Niepoprawna. To techniki bialoskrzynkowe."}},

{n:36,id:"P36",ch:4,lo:"FL-4.2.1",k:"K3",sel:1,
 scenario:"<p>Pole „wiek” akceptuje liczby calkowite. Regula: ponizej 18 = odrzucenie, 18-65 = standard, powyzej 65 = senior.</p>",
 q:"Stosujac podzial na klasy rownowaznosci, ktory zestaw wartosci reprezentuje trzy ROZNE poprawne klasy (po jednej z kazdej)?",
 opts:[["a","10, 15, 17"],
   ["b","12, 40, 70"],
   ["c","18, 40, 65"],
   ["d","66, 80, 99"]],
 correct:["b"],
 exp:{_:"Klasy rownowaznosci: [ <18 ], [ 18-65 ], [ >65 ]. Aby pokryc kazda klasa raz, potrzebna jest jedna wartosc z kazdego przedzialu.",
   a:"Niepoprawna. Wszystkie trzy naleza do klasy <18.",
   b:"Poprawna. 12 (<18), 40 (18-65), 70 (>65) — po jednym przedstawicielu z kazdej z trzech klas.",
   c:"Niepoprawna. 18 i 65 naleza do tej samej klasy (18-65).",
   d:"Niepoprawna. Wszystkie trzy naleza do klasy >65."}},

{n:37,id:"P37",ch:4,lo:"FL-4.2.2",k:"K3",sel:1,
 scenario:"<p>Pole przyjmuje liczby calkowite z zakresu od 1 do 100 (wlacznie).</p>",
 q:"Stosujac dwuwartosciowa analize wartosci brzegowych (BVA), ktore wartosci nalezy przetestowac dla DOLNEJ granicy?",
 opts:[["a","0 i 1"],
   ["b","1 i 2"],
   ["c","0 i 2"],
   ["d","Tylko 1"]],
 correct:["a"],
 exp:{_:"Dwuwartosciowa BVA testuje wartosc graniczna oraz wartosc tuz poza nia. Dla dolnej granicy 1 sa to: 1 (granica, poprawna) i 0 (tuz ponizej, niepoprawna).",
   a:"Poprawna. 0 (tuz ponizej granicy) i 1 (granica) — para wartosci brzegowych dla dolnej granicy.",
   b:"Niepoprawna. 2 nie jest wartoscia brzegowa dla dolnej granicy (to zwykla wartosc wewnatrz zakresu).",
   c:"Niepoprawna. 2 nie jest brzegiem dolnej granicy.",
   d:"Niepoprawna. Trzeba przetestowac obie strony granicy."}},

{n:38,id:"P38",ch:4,lo:"FL-4.2.2",k:"K3",sel:1,
 scenario:"<p>System ocen przyznaje rabat: zakup od 100 do 500 zl (wlacznie) = rabat 10%.</p>",
 q:"Ktory zestaw zawiera WSZYSTKIE wartosci brzegowe (3-wartosciowe BVA) dla GORNEJ granicy 500?",
 opts:[["a","499, 500, 501"],
   ["b","500, 501, 502"],
   ["c","498, 499, 500"],
   ["d","100, 500, 1000"]],
 correct:["a"],
 exp:{_:"Trzy-wartosciowa BVA dla granicy 500 obejmuje: 499 (tuz ponizej), 500 (granica) i 501 (tuz powyzej).",
   a:"Poprawna. 499, 500, 501 — wartosc graniczna oraz po jednej z kazdej strony.",
   b:"Niepoprawna. Brakuje 499 (tuz ponizej granicy).",
   c:"Niepoprawna. 498 nie jest wartoscia brzegowa; brakuje 501.",
   d:"Niepoprawna. To nie sa wartosci sasiadujace z granica."}},

{n:39,id:"P39",ch:4,lo:"FL-4.2.3",k:"K3",sel:1,
 scenario:"<p>Logowanie: dostep przyznawany TYLKO gdy login jest poprawny ORAZ haslo poprawne. W kazdym innym przypadku dostep odrzucony.</p>",
 q:"Ile UNIKALNYCH regul (kolumn) ma pelna tablica decyzyjna dla dwoch warunkow logicznych (login poprawny?, haslo poprawne?)?",
 opts:[["a","2"],["b","3"],["c","4"],["d","8"]],
 correct:["c"],
 exp:{_:"Dla 2 warunkow logicznych liczba kombinacji = 2^2 = 4. Tylko kombinacja (login=T, haslo=T) daje dostep; pozostale 3 odrzucaja.",
   a:"Niepoprawna. Za malo kombinacji.",
   b:"Niepoprawna. Pelna tablica ma 4 reguly, nie 3.",
   c:"Poprawna. 2 warunki logiczne daja 2^2 = 4 kombinacje (reguly).",
   d:"Niepoprawna. 8 odpowiadaloby 3 warunkom (2^3)."}},

{n:40,id:"P40",ch:4,lo:"FL-4.2.4",k:"K3",sel:1,
 scenario:"<p>Odtwarzacz: ze stanu ZATRZYMANY zdarzenie „play” przechodzi do ODTWARZANIE; z ODTWARZANIE „pause” -> WSTRZYMANY; z WSTRZYMANY „play” -> ODTWARZANIE; z ODTWARZANIE „stop” -> ZATRZYMANY.</p>",
 q:"Ktora sekwencja zdarzen jest PRAWIDLOWA (wszystkie przejscia istnieja) zaczynajac od stanu ZATRZYMANY?",
 opts:[["a","play -> pause -> play -> stop"],
   ["b","pause -> play -> stop"],
   ["c","stop -> play -> pause"],
   ["d","play -> stop -> pause"]],
 correct:["a"],
 exp:{_:"Start: ZATRZYMANY. play->ODTWARZANIE, pause->WSTRZYMANY, play->ODTWARZANIE, stop->ZATRZYMANY. Wszystkie przejscia zdefiniowane.",
   a:"Poprawna. Kazde przejscie istnieje w modelu i sekwencja jest spojna.",
   b:"Niepoprawna. Ze stanu ZATRZYMANY nie ma przejscia „pause”.",
   c:"Niepoprawna. Ze stanu ZATRZYMANY nie ma przejscia „stop”.",
   d:"Niepoprawna. Po „stop” jest stan ZATRZYMANY, z ktorego nie ma „pause”."}},

{n:41,id:"P41",ch:4,lo:"FL-4.3.1",k:"K2",sel:1,
 q:"Co mierzy pokrycie instrukcji (statement coverage)?",
 opts:[["a","Odsetek wykonanych galezi (rozgalezien) w kodzie"],
   ["b","Odsetek wykonalnych instrukcji kodu wykonanych przez testy"],
   ["c","Odsetek przetestowanych wymagan"],
   ["d","Odsetek pokrytych klas rownowaznosci"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To pokrycie galezi.",
   b:"Poprawna. Pokrycie instrukcji = (wykonane instrukcje wykonalne / wszystkie instrukcje wykonalne) x 100%.",
   c:"Niepoprawna. To miara czarnoskrzynkowa / sledzenia wymagan.",
   d:"Niepoprawna. To dotyczy techniki podzialu na klasy rownowaznosci."}},

{n:42,id:"P42",ch:4,lo:"FL-4.3.2",k:"K2",sel:1,
 q:"Ktore stwierdzenie o pokryciu galezi (branch coverage) jest poprawne?",
 opts:[["a","100% pokrycia galezi zawsze gwarantuje 0% pokrycia instrukcji"],
   ["b","100% pokrycia galezi implikuje 100% pokrycia instrukcji (jest silniejsze)"],
   ["c","Pokrycie galezi ignoruje instrukcje warunkowe (if, switch)"],
   ["d","Pokrycie galezi i instrukcji to dokladnie to samo"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Przeciwnie — pelne pokrycie galezi daje pelne pokrycie instrukcji.",
   b:"Poprawna. Pokrycie galezi jest silniejsze: osiagniecie 100% galezi gwarantuje 100% instrukcji (ale nie odwrotnie).",
   c:"Niepoprawna. Galezie wynikaja wlasnie z instrukcji decyzyjnych.",
   d:"Niepoprawna. To rozne miary; galezie sa silniejsze."}},

{n:43,id:"P43",ch:4,lo:"FL-4.3.3",k:"K2",sel:1,
 q:"Jaka jest wartosc testowania bialoskrzynkowego?",
 opts:[["a","Nie wymaga dostepu do kodu zrodlowego"],
   ["b","Uwzglednia cala implementacje, dzieki czemu moze wykryc defekty nawet bez jawnej specyfikacji oraz ujawnic kod nieosiagalny lub martwy"],
   ["c","Zastepuje testowanie czarnoskrzynkowe w pelni"],
   ["d","Dotyczy wylacznie wymagan biznesowych"]],
 correct:["b"],
 exp:{a:"Niepoprawna. White-box wymaga znajomosci struktury/kodu.",
   b:"Poprawna. Bazujac na strukturze, white-box moze wykryc defekty wynikajace z implementacji (np. sciezki niepokryte, martwy kod), nawet gdy specyfikacja jest niepelna.",
   c:"Niepoprawna. Obie grupy technik sie uzupelniaja.",
   d:"Niepoprawna. To domena technik czarnoskrzynkowych."}},

{n:44,id:"P44",ch:4,lo:"FL-4.4.1",k:"K2",sel:1,
 q:"Na czym polega zgadywanie bledow (error guessing)?",
 opts:[["a","Na losowym generowaniu danych wejsciowych"],
   ["b","Na wykorzystaniu wiedzy testera o tym, gdzie zwykle wystepuja defekty (typowe pomylki, wczesniejsze awarie), do tworzenia testow"],
   ["c","Na pokryciu wszystkich galezi w kodzie"],
   ["d","Na formalnym wyprowadzeniu przypadkow z tablicy decyzyjnej"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To nie to samo co testowanie losowe.",
   b:"Poprawna. Zgadywanie bledow opiera sie na wiedzy i doswiadczeniu testera dotyczacym typowych pomylek programistow i historii defektow; pomocne sa listy typowych bledow.",
   c:"Niepoprawna. To technika bialoskrzynkowa.",
   d:"Niepoprawna. To technika czarnoskrzynkowa (tablica decyzyjna)."}},

{n:45,id:"P45",ch:4,lo:"FL-4.4.2",k:"K2",sel:1,
 q:"Co najlepiej opisuje testowanie eksploracyjne?",
 opts:[["a","Z gory zdefiniowane, szczegolowo zapisane skrypty testowe wykonywane krok po kroku"],
   ["b","Jednoczesne uczenie sie o produkcie, projektowanie i wykonywanie testow; czesto z uzyciem kart testow (sesje testowe)"],
   ["c","Technika bialoskrzynkowa mierzaca pokrycie sciezek"],
   ["d","Wylacznie automatyczne testy regresji"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To testowanie skryptowe, przeciwienstwo eksploracji.",
   b:"Poprawna. W testach eksploracyjnych tester rownoczesnie poznaje produkt, projektuje i wykonuje testy; bywa zarzadzane sesjami (np. karty testow, time-box).",
   c:"Niepoprawna. To technika oparta na doswiadczeniu, nie bialoskrzynkowa.",
   d:"Niepoprawna. To nie automatyczna regresja."}},

{n:46,id:"P46",ch:4,lo:"FL-4.4.3",k:"K2",sel:1,
 q:"Jaka jest glowna cecha testowania opartego na listach kontrolnych (checklist-based)?",
 opts:[["a","Tester wyprowadza przypadki testowe z formalnego modelu stanu"],
   ["b","Tester projektuje i wykonuje testy w oparciu o liste warunkow/pozycji do sprawdzenia, bazujaca na doswiadczeniu"],
   ["c","Wymaga 100% pokrycia instrukcji"],
   ["d","Jest mozliwe tylko z dostepem do kodu zrodlowego"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To technika przejsc miedzy stanami (czarnoskrzynkowa).",
   b:"Poprawna. Testowanie oparte na listach kontrolnych uzywa listy pozycji do zweryfikowania (np. heurystyk, typowych ryzyk); listy buduje sie na doswiadczeniu.",
   c:"Niepoprawna. To miara bialoskrzynkowa.",
   d:"Niepoprawna. Nie wymaga kodu zrodlowego."}},

{n:47,id:"P47",ch:4,lo:"FL-4.5.1",k:"K2",sel:1,
 q:"Co opisuje kryterium INVEST przy pisaniu dobrych historyjek uzytkownika?",
 opts:[["a","Historyjka powinna byc Independent, Negotiable, Valuable, Estimable, Small, Testable"],
   ["b","Historyjka powinna zawierac co najmniej 100 slow"],
   ["c","Historyjke pisze wylacznie tester bez udzialu biznesu"],
   ["d","Historyjka nie wymaga kryteriow akceptacji"]],
 correct:["a"],
 exp:{a:"Poprawna. Dobra historyjka spelnia INVEST: niezalezna, negocjowalna, wartosciowa, mozliwa do oszacowania, mala i testowalna; tworzona we wspolpracy „trzech amigos” (biznes, deweloper, tester).",
   b:"Niepoprawna. Liczba slow nie jest kryterium.",
   c:"Niepoprawna. Historyjki powstaja we wspolpracy biznesu, programistow i testerow.",
   d:"Niepoprawna. Kryteria akceptacji sa istotnym elementem historyjki."}},

{n:48,id:"P48",ch:4,lo:"FL-4.5.2",k:"K2",sel:1,
 q:"Ktory format jest typowym sposobem zapisu kryteriow akceptacji w stylu opartym na scenariuszach?",
 opts:[["a","Given/When/Then (zakladajac/kiedy/wtedy)"],
   ["b","If/Else/EndIf"],
   ["c","Insert/Update/Delete"],
   ["d","Begin/Commit/Rollback"]],
 correct:["a"],
 exp:{a:"Poprawna. Format scenariuszowy Given/When/Then (np. w BDD) to jeden z dwoch glownych sposobow zapisu kryteriow akceptacji; drugi to styl oparty na regulach (lista warunkow).",
   b:"Niepoprawna. To konstrukcja programistyczna.",
   c:"Niepoprawna. To operacje na bazie danych.",
   d:"Niepoprawna. To operacje transakcyjne."}},

{n:49,id:"P49",ch:4,lo:"FL-4.5.3",k:"K3",sel:1,
 scenario:"<p>Kryterium akceptacji (ATDD): „Zakladajac, ze koszyk zawiera produkty za 200 zl, kiedy uzytkownik finalizuje zakup, wtedy naliczany jest darmowy transport (prog 150 zl)”.</p>",
 q:"Ktory przypadek testowy NAJLEPIEJ wyprowadza wartosc brzegowa zgodnie z tym kryterium w podejsciu ATDD?",
 opts:[["a","Koszyk za 149,99 zl -> oczekiwany: transport platny"],
   ["b","Koszyk za 200 zl -> oczekiwany: brak naliczenia"],
   ["c","Koszyk pusty -> oczekiwany: darmowy transport"],
   ["d","Koszyk za 500 zl -> oczekiwany: transport platny"]],
 correct:["a"],
 exp:{_:"W ATDD przypadki testowe wyprowadza sie z kryteriow akceptacji, w tym pozytywne, negatywne i brzegowe. Prog darmowego transportu to 150 zl.",
   a:"Poprawna. 149,99 zl to wartosc tuz ponizej progu — brzegowy przypadek negatywny: transport powinien byc platny.",
   b:"Niepoprawna. 200 zl >= 150 zl, wiec transport powinien byc darmowy, nie „brak naliczenia”.",
   c:"Niepoprawna. Pusty koszyk nie spelnia progu — nie powinien dawac darmowego transportu.",
   d:"Niepoprawna. 500 zl >= 150 zl, wiec transport jest darmowy, nie platny."}},

/* ================= ROZDZIAL 5 — Zarzadzanie dzialaniami testowymi ================= */
{n:50,id:"P50",ch:5,lo:"FL-5.1.1",k:"K2",sel:1,
 q:"Co zawiera typowy plan testow?",
 opts:[["a","Wylacznie liste defektow znalezionych w projekcie"],
   ["b","Cele i zakres testow, podejscie, zasoby i harmonogram, kryteria wejscia/wyjscia oraz ryzyka i ich obsluge"],
   ["c","Tylko kod zrodlowy przypadkow testowych"],
   ["d","Jedynie dane logowania do srodowiska testowego"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Lista defektow to nie plan testow.",
   b:"Poprawna. Plan testow dokumentuje m.in.: cele i zakres, podejscie testowe, zasoby, harmonogram, kryteria wejscia i wyjscia, ryzyka. Wspiera komunikacje i sterowanie testowaniem.",
   c:"Niepoprawna. Plan to nie kod przypadkow.",
   d:"Niepoprawna. To zbyt waski element."}},

{n:51,id:"P51",ch:5,lo:"FL-5.1.2",k:"K1",sel:1,
 q:"Jak tester dodaje wartosc podczas planowania iteracji i wydania?",
 opts:[["a","Podejmuje decyzje biznesowe o zakresie wydania zamiast wlasciciela produktu"],
   ["b","Uczestniczy w estymacji, ocenie testowalnosci historyjek i ryzyk oraz pomaga doprecyzowac kryteria akceptacji"],
   ["c","Zajmuje sie wylacznie wykonywaniem testow po zakonczeniu iteracji"],
   ["d","Nie bierze udzialu w planowaniu"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Decyzje o zakresie nalezy do wlasciciela produktu.",
   b:"Poprawna. Tester wnosi wartosc w planowaniu: ocenia testowalnosc i ryzyka, uczestniczy w estymacji, pomaga uszczegolowic historyjki i kryteria akceptacji.",
   c:"Niepoprawna. Udzial testera jest cenny juz w planowaniu.",
   d:"Niepoprawna. Tester aktywnie uczestniczy w planowaniu."}},

{n:52,id:"P52",ch:5,lo:"FL-5.1.3",k:"K2",sel:1,
 q:"Czym roznia sie kryteria wejscia od kryteriow wyjscia?",
 opts:[["a","Kryteria wejscia okreslaja, kiedy zakonczyc testowanie; wyjscia — kiedy je rozpoczac"],
   ["b","Kryteria wejscia okreslaja warunki rozpoczecia danej czynnosci; kryteria wyjscia — warunki uznania jej za zakonczona"],
   ["c","Oba pojecia oznaczaja to samo"],
   ["d","Kryteria wyjscia dotycza tylko srodowiska testowego"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Definicje odwrocone.",
   b:"Poprawna. Kryteria wejscia (definition of ready) musza byc spelnione, by rozpoczac czynnosc; kryteria wyjscia (definition of done) — by uznac ja za ukonczona.",
   c:"Niepoprawna. To rozne pojecia.",
   d:"Niepoprawna. Dotycza calej czynnosci, nie tylko srodowiska."}},

{n:53,id:"P53",ch:5,lo:"FL-5.1.4",k:"K3",sel:1,
 scenario:"<p>Zespol szacuje pracochlonnosc metoda trzypunktowa (PERT). Estymaty: optymistyczna a=6 dni, najbardziej prawdopodobna m=9 dni, pesymistyczna b=18 dni.</p>",
 q:"Jaka jest estymata oczekiwana E wedlug wzoru E = (a + 4m + b) / 6?",
 opts:[["a","9 dni"],["b","10 dni"],["c","11 dni"],["d","12 dni"]],
 correct:["b"],
 exp:{_:"E = (a + 4m + b) / 6 = (6 + 4*9 + 18) / 6 = (6 + 36 + 18) / 6 = 60 / 6 = 10 dni.",
   a:"Niepoprawna. To wartosc najbardziej prawdopodobna m, nie estymata oczekiwana.",
   b:"Poprawna. (6 + 36 + 18) / 6 = 60 / 6 = 10 dni.",
   c:"Niepoprawna. Bledne podstawienie do wzoru.",
   d:"Niepoprawna. Bledne podstawienie do wzoru."}},

{n:54,id:"P54",ch:5,lo:"FL-5.1.5",k:"K3",sel:1,
 scenario:"<p>Do wykonania zostaly 4 przypadki testowe. Priorytetyzujesz wg ryzyka (najpierw najwyzsze ryzyko). Ryzyka: T1=niskie, T2=wysokie, T3=srednie, T4=wysokie (ale T4 zalezy od wczesniejszego wykonania T2).</p>",
 q:"Ktora kolejnosc wykonania jest najlepsza przy priorytetyzacji opartej na ryzyku z uwzglednieniem zaleznosci?",
 opts:[["a","T1, T3, T2, T4"],
   ["b","T2, T4, T3, T1"],
   ["c","T4, T2, T3, T1"],
   ["d","T3, T1, T2, T4"]],
 correct:["b"],
 exp:{_:"Najpierw najwyzsze ryzyko (T2, T4), ale T4 zalezy od T2, wiec T2 przed T4. Potem srednie (T3), na koncu niskie (T1).",
   a:"Niepoprawna. Zaczyna od najnizszego ryzyka.",
   b:"Poprawna. T2 (wysokie, brak zaleznosci) -> T4 (wysokie, zalezne od T2) -> T3 (srednie) -> T1 (niskie).",
   c:"Niepoprawna. T4 nie moze byc przed T2 (zaleznosc).",
   d:"Niepoprawna. Srednie/niskie ryzyko przed wysokim."}},

{n:55,id:"P55",ch:5,lo:"FL-5.1.6",k:"K1",sel:1,
 q:"Co przedstawia piramida testow?",
 opts:[["a","Im wyzszy poziom piramidy, tym wiecej szczegolowych testow jednostkowych"],
   ["b","Wiele szybkich testow niskiego poziomu (jednostkowych) u podstawy, a mniej wolniejszych testow wysokiego poziomu (np. UI/E2E) na gorze"],
   ["c","Tylko testy manualne na kazdym poziomie"],
   ["d","Rownomiernie tyle samo testow na kazdym poziomie"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Testow jednostkowych jest najwiecej u podstawy (dol piramidy).",
   b:"Poprawna. Piramida testow: duzo szybkich, tanich testow jednostkowych u podstawy, mniej testow integracyjnych wyzej, najmniej wolnych testow przez UI/E2E na szczycie.",
   c:"Niepoprawna. Piramida zaklada silna automatyzacje.",
   d:"Niepoprawna. Rozklad jest celowo nierowny (wiecej u dolu)."}},

{n:56,id:"P56",ch:5,lo:"FL-5.1.7",k:"K2",sel:1,
 q:"Czemu sluza kwadranty testowe (testing quadrants)?",
 opts:[["a","Do pomiaru pokrycia instrukcji w kodzie"],
   ["b","Do grupowania poziomow i typow testow wedlug tego, czy wspieraja zespol czy oceniaja produkt, oraz czy sa zorientowane biznesowo czy technicznie"],
   ["c","Do szacowania budzetu projektu"],
   ["d","Do priorytetyzacji defektow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To miara bialoskrzynkowa.",
   b:"Poprawna. Kwadranty testowe (Brian Marick) porzadkuja testy wg dwoch osi: wspieraja zespol vs oceniaja produkt oraz zorientowane biznesowo vs technicznie; lacza poziomy i typy testow.",
   c:"Niepoprawna. Nie sluza do budzetowania.",
   d:"Niepoprawna. Nie sluza do priorytetyzacji defektow."}},

{n:57,id:"P57",ch:5,lo:"FL-5.2.1",k:"K1",sel:1,
 q:"Jak wyznacza sie poziom ryzyka?",
 opts:[["a","Jako sume liczby defektow i liczby przypadkow testowych"],
   ["b","Jako kombinacje prawdopodobienstwa (likelihood) wystapienia ryzyka oraz jego wplywu (impact)"],
   ["c","Wylacznie na podstawie liczby linii kodu"],
   ["d","Jako roznice miedzy estymata a czasem rzeczywistym"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To nie definicja poziomu ryzyka.",
   b:"Poprawna. Poziom ryzyka = prawdopodobienstwo wystapienia x wielkosc szkody (wplyw). Im wyzsze oba, tym wyzsze ryzyko.",
   c:"Niepoprawna. LOC nie definiuje poziomu ryzyka.",
   d:"Niepoprawna. To metryka estymacji, nie ryzyka."}},

{n:58,id:"P58",ch:5,lo:"FL-5.2.2",k:"K2",sel:1,
 q:"Ktory przyklad jest RYZYKIEM PROJEKTOWYM (a nie produktowym)?",
 opts:[["a","Aplikacja moze zwracac bledne wyniki obliczen finansowych"],
   ["b","Opoznienie dostawy z powodu niedostepnosci kluczowego srodowiska testowego i braku zasobow"],
   ["c","System moze byc podatny na atak SQL injection"],
   ["d","Funkcja platnosci moze nie dzialac dla niektorych kart"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To ryzyko produktowe (jakosc produktu).",
   b:"Poprawna. Ryzyka projektowe dotycza zarzadzania i realizacji projektu: zasoby, harmonogram, srodowiska, dostawcy, organizacja.",
   c:"Niepoprawna. To ryzyko produktowe (bezpieczenstwo).",
   d:"Niepoprawna. To ryzyko produktowe (funkcjonalnosc)."}},

{n:59,id:"P59",ch:5,lo:"FL-5.2.3",k:"K2",sel:1,
 q:"Jak analiza ryzyka produktowego wplywa na testowanie?",
 opts:[["a","Nie ma zadnego wplywu na zakres testow"],
   ["b","Obszary wyzszego ryzyka testuje sie dokladniej i wczesniej, obszarom nizszego ryzyka poswieca sie mniej wysilku"],
   ["c","Wszystkie obszary testuje sie zawsze tak samo dokladnie"],
   ["d","Im wyzsze ryzyko, tym mniej testow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Ryzyko silnie wplywa na zakres i intensywnosc.",
   b:"Poprawna. Analiza ryzyka produktowego kieruje dokladnoscia i zakresem: wiecej i wczesniej tam, gdzie ryzyko wysokie; mniej tam, gdzie niskie. Pomaga tez priorytetyzowac.",
   c:"Niepoprawna. To zaprzecza idei testowania opartego na ryzyku.",
   d:"Niepoprawna. Wyzsze ryzyko -> wiecej (nie mniej) testow."}},

{n:60,id:"P60",ch:5,lo:"FL-5.2.4",k:"K2",sel:1,
 q:"Ktora czynnosc jest srodkiem zaradczym (response) na zidentyfikowane ryzyko PRODUKTOWE?",
 opts:[["a","Zmiana terminu wyplaty wynagrodzen zespolu"],
   ["b","Zaprojektowanie i wykonanie dodatkowych testow w obszarze wysokiego ryzyka oraz przeglady tego obszaru"],
   ["c","Zakup nowych krzesel biurowych"],
   ["d","Zignorowanie ryzyka"]],
 correct:["b"],
 exp:{a:"Niepoprawna. To nie dotyczy ryzyka produktowego.",
   b:"Poprawna. Reakcje na ryzyko produktowe to m.in.: dokladniejsze testowanie obszarow wysokiego ryzyka, wybor odpowiednich technik, przeglady, wczesniejsze zaangazowanie testerow.",
   c:"Niepoprawna. Bez zwiazku z ryzykiem produktowym.",
   d:"Niepoprawna. Ryzyk nie nalezy ignorowac."}},

{n:61,id:"P61",ch:5,lo:"FL-5.3.1",k:"K1",sel:1,
 q:"Ktore z ponizszych jest typowa metryka testowa?",
 opts:[["a","Liczba pracownikow w dziale kadr"],
   ["b","Procent wykonanych przypadkow testowych oraz gestosc defektow"],
   ["c","Kolor logo aplikacji"],
   ["d","Liczba spotkan zarzadu w kwartale"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Nieistotna dla testowania.",
   b:"Poprawna. Metryki testowe obejmuja m.in.: postep wykonania przypadkow, pokrycie, liczbe i gestosc defektow, metryki ryzyka, koszt testowania.",
   c:"Niepoprawna. Nie jest metryka.",
   d:"Niepoprawna. Nie jest metryka testowa."}},

{n:62,id:"P62",ch:5,lo:"FL-5.3.2",k:"K2",sel:1,
 q:"Czym rozni sie raport o postepie testow (test progress report) od raportu koncowego (test completion report)?",
 opts:[["a","Raport o postepie tworzy sie tylko po zakonczeniu wszystkich testow"],
   ["b","Raport o postepie wspiera biezace sterowanie w trakcie testowania; raport koncowy podsumowuje zakonczone testy (np. dla danego etapu/wydania)"],
   ["c","Oba raporty maja identyczna tresc i odbiorcow"],
   ["d","Raport koncowy powstaje na poczatku projektu"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Raport o postepie powstaje w trakcie, cyklicznie.",
   b:"Poprawna. Raport o postepie sluzy biezacemu monitorowaniu i sterowaniu; raport koncowy podsumowuje wykonane testy po osiagnieciu kryteriow wyjscia lub na koniec etapu.",
   c:"Niepoprawna. Roznia sie celem, trescia i czesto odbiorcami.",
   d:"Niepoprawna. Raport koncowy powstaje na koniec, nie na poczatku."}},

{n:63,id:"P63",ch:5,lo:"FL-5.3.3",k:"K2",sel:1,
 q:"Co warto uwzglednic, komunikujac status testowania roznym odbiorcom?",
 opts:[["a","Zawsze te same szczegoly techniczne niezaleznie od odbiorcy"],
   ["b","Dostosowanie poziomu szczegolowosci i formy do odbiorcy (np. zarzad oczekuje podsumowania ryzyk, zespol — szczegolow technicznych)"],
   ["c","Komunikowanie statusu wylacznie na koniec projektu"],
   ["d","Pomijanie informacji o ryzykach"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Forme nalezy dostosowac do odbiorcy.",
   b:"Poprawna. Status komunikuje sie roznymi kanalami i z rozna szczegolowoscia w zaleznosci od odbiorcy i celu (np. dashboardy, raporty, spotkania).",
   c:"Niepoprawna. Status komunikuje sie na biezaco.",
   d:"Niepoprawna. Ryzyka sa istotna czescia komunikacji."}},

{n:64,id:"P64",ch:5,lo:"FL-5.4.1",k:"K2",sel:1,
 q:"Jak zarzadzanie konfiguracja (configuration management) wspiera testowanie?",
 opts:[["a","Zastepuje potrzebe pisania przypadkow testowych"],
   ["b","Zapewnia jednoznaczna identyfikacje i wersjonowanie elementow (kodu, testaliow, srodowisk) oraz ich powiazan, dzieki czemu testy sa powtarzalne i identyfikowalne"],
   ["c","Sluzy wylacznie do mierzenia wydajnosci systemu"],
   ["d","Dotyczy tylko kodu produkcyjnego, nie testaliow"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Nie zastepuje projektowania testow.",
   b:"Poprawna. Zarzadzanie konfiguracja identyfikuje i kontroluje wersje przedmiotow testow i testaliow oraz ich powiazania, co zapewnia powtarzalnosc i identyfikowalnosc testow.",
   c:"Niepoprawna. To nie pomiar wydajnosci.",
   d:"Niepoprawna. Obejmuje takze testalia (przypadki, dane, skrypty, srodowiska)."}},

{n:65,id:"P65",ch:5,lo:"FL-5.5.1",k:"K3",sel:1,
 scenario:"<p>Tester zglasza defekt po wykryciu, ze przy probie zapisu formularza z poprawnymi danymi aplikacja wyswietla blad 500.</p>",
 q:"Ktory element jest NIEZBEDNY w dobrym raporcie o defekcie, aby umozliwic reprodukcje?",
 opts:[["a","Imie i nazwisko programisty, ktory napisal kod"],
   ["b","Kroki reprodukcji, wynik oczekiwany i wynik faktyczny oraz srodowisko, w ktorym wystapil defekt"],
   ["c","Liczba defektow znalezionych przez tester w zeszlym miesiacu"],
   ["d","Ocena pracy zespolu deweloperskiego"]],
 correct:["b"],
 exp:{_:"Raport o defekcie powinien umozliwic reprodukcje i ocene wplywu: identyfikator, opis, kroki, wynik oczekiwany vs faktyczny, srodowisko, stopien istotnosci/priorytet, status.",
   a:"Niepoprawna. Wskazywanie winnego nie jest celem raportu.",
   b:"Poprawna. Kroki reprodukcji, wynik oczekiwany i faktyczny oraz dane o srodowisku sa kluczowe do odtworzenia i diagnozy defektu.",
   c:"Niepoprawna. To metryka, nie element pojedynczego raportu.",
   d:"Niepoprawna. Raport opisuje defekt, nie ocenia ludzi."}},

/* ================= ROZDZIAL 6 — Narzedzia wspomagajace testowanie ================= */
{n:66,id:"P66",ch:6,lo:"FL-6.1.1",k:"K2",sel:1,
 q:"W jaki sposob narzedzia do zarzadzania testami wspieraja testowanie?",
 opts:[["a","Automatycznie naprawiaja defekty w kodzie"],
   ["b","Wspieraja zarzadzanie przypadkami, identyfikowalnosc z wymaganiami, planowanie i raportowanie postepu oraz zarzadzanie defektami"],
   ["c","Zastepuja potrzebe analizy i projektowania testow"],
   ["d","Sluza wylacznie do kompilacji kodu produkcyjnego"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Narzedzia nie naprawiaja kodu.",
   b:"Poprawna. Narzedzia wspierajace testowanie pomagaja m.in. w zarzadzaniu testami i defektami, identyfikowalnosci, projektowaniu i wykonywaniu testow, w testach statycznych i wydajnosciowych.",
   c:"Niepoprawna. Nie zastepuja pracy analitycznej testera.",
   d:"Niepoprawna. To zbyt waskie i niezgodne z celem."}},

{n:67,id:"P67",ch:6,lo:"FL-6.2.1",k:"K1",sel:1,
 q:"Ktore stwierdzenie jest RYZYKIEM (a nie korzyscia) automatyzacji testow?",
 opts:[["a","Zmniejszenie powtarzalnej pracy manualnej"],
   ["b","Bardziej spojne i powtarzalne wykonanie testow"],
   ["c","Koszt i wysilek utrzymania skryptow testowych przy zmianach w oprogramowaniu oraz ryzyko nadmiernych oczekiwan"],
   ["d","Szybsza informacja zwrotna z testow regresji"]],
 correct:["c"],
 exp:{a:"Niepoprawna. To korzysc automatyzacji.",
   b:"Niepoprawna. To korzysc automatyzacji.",
   c:"Poprawna. Ryzyka automatyzacji: koszt wdrozenia i utrzymania, kruche skrypty wymagajace aktualizacji przy zmianach, nierealistyczne oczekiwania, niedoszacowanie zlozonosci narzedzia.",
   d:"Niepoprawna. To korzysc automatyzacji."}},

{n:68,id:"P68",ch:6,lo:"FL-6.2.1",k:"K1",sel:1,
 q:"Ktora z ponizszych jest typowa KORZYSCIA z automatyzacji testow?",
 opts:[["a","Calkowite wyeliminowanie potrzeby testowania manualnego i eksploracyjnego"],
   ["b","Wykonywanie duzej liczby testow regresji szybciej, czesciej i bardziej powtarzalnie niz manualnie"],
   ["c","Gwarancja braku defektow w oprogramowaniu"],
   ["d","Brak jakichkolwiek kosztow poczatkowych"]],
 correct:["b"],
 exp:{a:"Niepoprawna. Automatyzacja nie zastepuje testow eksploracyjnych/manualnych.",
   b:"Poprawna. Korzysci: oszczednosc czasu na powtarzalnych testach (np. regresja), wieksza spojnosc i powtarzalnosc, szybsza informacja zwrotna, ocena obiektywna (metryki).",
   c:"Niepoprawna. Nic nie gwarantuje braku defektow.",
   d:"Niepoprawna. Automatyzacja ma istotne koszty poczatkowe i utrzymania."}},

];
